### ISSUE TITLE
[Bug]: 签名服务器没了..

### ISSUE THREAD

**Issue by dfaofeng** [LagrangeDev/go-cqhttp#9]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

0e764e1

### 运行环境

Linux

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

0 | Default

### 重现步骤

打包为docker版本,运行,昨天还好好的,今天就提示sign服务返回error

### 期望的结果是什么？

sign服务返回正常

### 实际的结果是什么？

返回 "error_code": 1

**Comment by dfaofeng** [comment]
运行报错信息 
```
[2024-10-23 09:17:41] [INFO]: 扫码成功, 请在手机端确认登录. 
[2024-10-23 09:17:47] [ERROR]: Protocol -> [client.(*QQClient).QRCodeLogin] all sign service down 
[2024-10-23 09:17:47] [FATAL]: 登录时发生致命错误: all sign service down
```

**Comment by dfaofeng** [comment]
不知道能不能用 https://qsign-guide.trpgbot.com/ 这个里面的sign服务器

**Comment by Redmomn** [comment]
签名服务器都在cf上部署，请自行检查连通性

**Comment by Redmomn** [comment]
> 不知道能不能用 https://qsign-guide.trpgbot.com/ 这个里面的sign服务器

不行，这个是安卓协议的签名

**Comment by dfaofeng** [comment]
> 签名服务器都在cf上部署，请自行检查连通性

https://sign.ciallo.site/api/sign 这个返回为"error_code": 1 能修吗?

**Comment by Redmomn** [comment]
这个是正常的，因为你请求没有带参数

**Comment by dfaofeng** [comment]
> 这个是正常的，因为你请求没有带参数

你肯定后台修了服务的....刚一直失败,现在好了..

**Comment by 666dechaoge** [comment]
如何搭建LagrangeDev/go-cqhttp可用的sign

**Comment by Redmomn** [comment]
不提供自建

**Comment by 666dechaoge** [comment]
![Image](https://github.com/user-attachments/assets/aec0196b-1bec-4f96-88d0-e43c3cf16a58)那这个怎么填

**Comment by Redmomn** [comment]
https://github.com/LagrangeDev/Lagrange.Core/blob/9b17694773272fbd60e5362d8ed8af50ab23f181/Lagrange.Core/Utility/Sign/LinuxSigner.cs#L5
